### PR TITLE
switch around the folder structure

### PR DESCRIPTION
**Pull request by mattgreenfield**
Proposal for renaming and reordering files to match the below structure.
- `/toolkit/`
- `/component/`
- `variables.scss` - default variables
- `boilerplate.scss` - imports all of the above, becuase `@import "boilerplate/boilerplate";` is nice.

I've also create the `boilerplate-output.css` file which is everything in the boilerplate compiled in to CSS, without running / including any of the mixins. I doesn't belong in the master branch but it might be handy in the development branch? I'm not precious though, can deleted once viewed...

@benjaminparry 

Theres a branch on html too just to change how it imports the boilerplate.

### CODE REVIEW

**Comment by Dayjo** [comment]
Seems like a good idea.

**Comment by benjaminparry** [comment]
The `boilerplate.scss` would be nice in an example project folder perhaps. I personally think we want to encourage a modular inclusion of those includes, this is as much us pinning-down the desired development flow.

**Comment by benjaminparry** [comment]
Do you think the `silent` naming convention is superfluous then?

**Comment by mattgreenfield** [comment]
`boilerplate.scss` came from the way that other frameworks do things but we can always be different.
eg. https://github.com/zurb/foundation/blob/master/scss/foundation.scss

I think the `silent` and `silent-extends` could do with a bit of working out, I like the idea of using the same or very similar toolkit for templates and core (at least for folder structure and workflow), I wonder if we'll ever have problems with clashing of class names like we did with page builder edit-mode. If they are going to be different though maybe they should be **really** different, prefixed maybe?

We should sit down and work it out on paper I think.

**Comment by benjaminparry** [comment]
Yeah I’d like to do this before the next two templates get merged in.

**Pull request closed without merging**
